### ISSUE TITLE
"Source code" doesn't work in modal with tinymce

### ISSUE THREAD

**Issue by MaximShaikovskiy** [TrestleAdmin/trestle#503]
If you open this modal in a modal, you cannot print in it. The browser does not show any errors.
[Screencast from 2024-09-26 10-20-09.webm](https://github.com/user-attachments/assets/b26c59a3-ce57-4cae-93ae-320d3bc50f1f)

**Comment by spohlenz** [comment]
What versions of trestle, tinymce-rails and trestle-tinymce are you using? This looks like an issue I encountered not too long ago, but should be fixed in the latest releases.

**Comment by MaximShaikovskiy** [comment]
```
gem 'trestle', '0.10.0.pre'
gem 'trestle-tinymce', '0.4.0.pre'
  tinymce-rails (~> 5.1)
```

**Comment by spohlenz** [comment]
That'll be it -- the specific fixes made it into the non-pre releases of trestle 0.10.0 and trestle-tinymce 0.4.0. Updating to those should hopefully fix it for you.

**Comment by MaximShaikovskiy** [comment]
But only in pre is the menu on the left normally displayed with hyphens, while in others their names are covered by main-content-area
![Screenshot from 2024-09-12 13-17-44](https://github.com/user-attachments/assets/cb17b646-52cd-42da-a572-b168211918ea)

**Comment by spohlenz** [comment]
Give this CSS snippet a try in `app/assets/stylesheets/custom.css`. It will re-enable text wrapping in the sidebar, at the cost of consistent icon alignment when the sidebar is expanded/collapsed.

```css
.app-nav .nav-label {
  white-space: normal;
}

@media (min-width: 1200px) {
  .sidebar-collapsed .app-nav .nav-label {
    white-space: nowrap;
  }
}

@media (min-width: 768px) and (max-width: 1199.98px) {
  .app-nav .nav-label {
    white-space: nowrap;
  }

  .sidebar-expanded .app-nav .nav-label {
    white-space: normal;
  }
}
```
